import Head from 'next/head'
import Hero from '../components/Hero'
import Services from '../components/Services'
import Dishes from '../components/Dishes'
import { getDishes } from '../services'
import { Discount } from '../components'


export default function Home({ dishes }) {
  return (
    <>
      <Head>
        <title>Delve | Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div className=''>
        {/* Layout */}

        <Hero />
        <Services />
        <div>
          <div className='flex flex-col items-center justify-center ml-3  sm:ml-0'>
            <h2 className='text-3xl font-semibold text-neutral-900 mb-4'>
              Our Menu
            </h2>
            <span className='text-neutral-700 font-semibold'>
              Menu that always  make you fall in love
            </span>
          </div>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 items-center justify-center py-6 px-4 sm:px-20'>
            {dishes.map((dish) => (
              <Dishes dish={dish.node} key={dish.id} />
            ))}
          </div>
        </div>

        <Discount />

      </div>

    </>
  )
}


export async function getStaticProps() {
  const dishes = (await getDishes()) || [];

  return {
    props: { dishes }
  }
}